# -----------------------------------------------------------------------------
#
# AMBER extras integration for Home Assistant Energy Management. 
# Requires HA Amber Electric Integration to be installed.
# 
# Developed by Peter Hormann
#
# Created: 9-Feb-2023
#
# Last updated: 2-Jun-2023
#
# Updates: 
#   2-Jun-23 - improved error checking for when nem_date is not defined.
#
# Creates a new "amber_forecast" sensor which contains the curent time and 24 hours 
# future time in 30 minute increments, the general forecast prices and the feed-in 
# forecast prices stored in an array format suitable for use by a Apex Chart card 
# (installed via HACS) - see <amber_forecast_chart.yaml> for the card YAML code.
#
# Installation: 
#   1. Copy this yaml file to the HA config directory.
#   2. Include this file name as a package in the HA <configuration.yaml>. 
#      For example -
#        packages:
#          pack_1: !include amber_forecast.yaml
#   3. Rename "amber12ayrst_xyz" sensors to match HA Amber installation device naming.
#   4. Ensure the Developer Tools > YAML > Check Configuration passes without error.
#   5. Restart HA, or simply use YAML Configuration Reloading > Template Entities.
#   6. Enjoy!
#
# If you find my work useful, please buy me a coffee ... thank you!
#   https://www.buymeacoffee.com/peter24x7
#
# Reference for more information and updates:
#   https://github.com/PeterH24x7/-Solar-Analytics-integration-for-Home-Assistant-Energy-monitoring
#
# -----------------------------------------------------------------------------

sensor:
  - platform: template
    sensors:
      amber_forecast:
        friendly_name: Amber Forecast
        unique_id: amber_forecast
        icon_template: mdi:chart-line
        value_template: >
          {%- if state_attr('sensor.amber12ayrst_general_price', 'nem_date')|is_defined -%}
            {{- as_local(as_datetime(states.sensor.amber12ayrst_general_price.attributes.nem_date) 
                - timedelta(minutes=30)).strftime("%Y-%m-%d %H:%M:%S")  
              -}}
          {%- else -%}
            {{- states.sensor.amber_forecast.state
                if states.sensor.amber_forecast.state|is_defined
                else 'unavailable'
              -}} 
          {%- endif -%}
        attribute_templates: 
          times: >
            {%- if states.sensor.amber12ayrst_general_price.attributes.nem_date|is_defined -%}
              {%- set ns = namespace( times = [ as_local( as_datetime( states.sensor.amber12ayrst_general_price.attributes.nem_date) 
                  - timedelta(minutes=30)).strftime("%Y-%m-%d %H:%M:%S") ] ) -%}
              {%- set today = state_attr('sensor.amber12ayrst_general_forecast','forecasts') -%}
              {%- for hours in today -%}
                {%- set ns.times = ns.times + [ as_local( as_datetime(hours.nem_date) - timedelta(minutes=30)).strftime("%Y-%m-%d %H:%M:%S") ] -%}
              {%- endfor -%}
              {{ ns.times }}
            {%- else -%}
              {{- states.sensor.amber_forecast.attributes.times
                if states.sensor.amber_forecast.attributes.times|is_defined
                else 'unavailable'
              -}} 
            {%- endif -%}
          general_price: >
            {%- if states.sensor.amber12ayrst_general_price.attributes.nem_date|is_defined -%}
              {%- set ns = namespace( general = [ ( states.sensor.amber12ayrst_general_price.state|float ) ] ) -%}
              {%- set today = state_attr('sensor.amber12ayrst_general_forecast','forecasts') -%}
              {%- for hours in today -%}
                {%- set ns.general = ns.general + [(hours.per_kwh)] -%}
              {%- endfor -%}
              {{ ns.general }}
            {%- else -%}
              {{- states.sensor.amber_forecast.attributes.general_price
                if states.sensor.amber_forecast.attributes.general_price|is_defined
                else 'unavailable'
              -}} 
            {%- endif -%}          
          fit_price: >
            {%- if states.sensor.amber12ayrst_general_price.attributes.nem_date|is_defined -%}
              {%- set ns = namespace( fit = [ ( states.sensor.amber12ayrst_general_price.attributes.spot_per_kwh|float ) ] ) -%}
              {%- set today = state_attr('sensor.amber12ayrst_general_forecast','forecasts') -%}
              {%- for hours in today -%}
                {%- set ns.fit = ns.fit + [(hours.spot_per_kwh)] -%}
              {%- endfor -%}
              {{ ns.fit }}
            {%- else -%}
              {{- states.sensor.amber_forecast.attributes.fit_price
                if states.sensor.amber_forecast.attributes.fit_price|is_defined
                else 'unavailable'
              -}} 
            {%- endif -%}          
          renewables_percent: >
            {%- if states.sensor.amber12ayrst_general_price.attributes.nem_date|is_defined -%}
              {%- set ns = namespace( renewables = [ ( states.sensor.amber12ayrst_general_price.attributes.renewables|float ) ] ) -%}
              {%- set today = state_attr('sensor.amber12ayrst_general_forecast','forecasts') -%}
              {%- for hours in today -%}
                {%- set ns.renewables = ns.renewables + [(hours.renewables)] -%}
              {%- endfor -%}
              {{ ns.renewables }}
            {%- else -%}
              {{- states.sensor.amber_forecast.attributes.renewables_percent
                if states.sensor.amber_forecast.attributes.renewables_percent|is_defined
                else 'unavailable'
              -}} 
            {%- endif -%}          

# -----------------------------------------------------------------------------
