# -----------------------------------------------------------------------------
#
# Heating Cooling integration for Home Assistant Energy Management. 
# Requires <solar_analytics.yaml> to be installed or an alternative source
# of Watt-hour charging data.
# 
# Developed by Peter Hormann
#
# Created: 20-Apr-2023
#
# Last updated: 2-Jun-2023
#
# Updates: 
#   18-May-23 - fixed meter resetting based on daily trigger at midnight.
#   2-Jun-23  - fixed error detection.
#
# Calculate Heating Cooling cost for both generated and imported energy, total net 
# cost and average combined charging rate for the day.
#
# If not using Solar Analytics, this integration requires a source of vehicle charged 
# generated or imported sources updated in 5 minute interval Watt-hours. A binary 
# sensor (replacing sa_data_by_5min_meter_reset) is also required to indicate if/when 
# the metering period has been reset - e.g. at midnight - must be true for one 5 
# minute interval.
#
# If not using the Amber Energy integration, then replace the last_price attribute
# with an alternative energy price sensor (or simply a constant - e.g. 0.25).
#
# Installation: 
#   1. Copy this yaml file to the HA config directory.
#   2. Include this file name as a package in the HA <configuration.yaml>. 
#      For example -
#        packages:
#          pack_2: !include amber_ev_charge_cost.yaml
#   3. Rename "amber12ayrst_xyz" sensors to match HA Amber installation sensor naming.
#   4. Ensure the Developer Tools > YAML > Check Configuration passes without error.
#   5. Restart HA, or simply use YAML Configuration Reloading > Template Entities.
#   6. Enjoy!
#
# If you find my work useful, please buy me a coffee ... thank you!
#   https://www.buymeacoffee.com/peter24x7
#
# Reference for more information and updates:
#   https://github.com/PeterH24x7/-Solar-Analytics-integration-for-Home-Assistant-Energy-monitoring
#
# -----------------------------------------------------------------------------

sensor:
  - platform: template
    sensors:
      amber_todays_heating_cooling_total_cost:
        friendly_name: "Heating Cooling Total Cost"
        unique_id: amber_todays_heating_cooling_total_cost
        unit_of_measurement: "AUD"
        device_class: "monetary"
        icon_template: mdi:cash
        value_template: >-
          {%- if states.sensor.sa_data_by_5min_load_air_conditioner_total.state|float(0.0) > 0.0 -%}
            {%- if states.sensor.amber_todays_heating_cooling_imported_cost.state|is_number 
                and states.sensor.amber_todays_heating_cooling_generated_cost.state|is_number -%}
              {{- states.sensor.amber_todays_heating_cooling_generated_cost.state|float(0.0)
                  + states.sensor.amber_todays_heating_cooling_imported_cost.state|float(0.0) 
                -}}
            {%- else -%}
              0.0
            {%- endif -%}
          {%- else -%}
            0.0
          {%- endif -%}
        attribute_templates: 
          state_class: total
          time_stamp: "{{- states.sensor.sa_data_by_5min_time_stamp.state -}}"

      amber_todays_heating_cooling_rate_av:
        friendly_name: "Heating Cooling Rate Average"
        unique_id: amber_todays_heating_cooling_rate_av
        unit_of_measurement: "$/kWh"
        device_class: "monetary"
        icon_template: mdi:cash-plus
        value_template: >-
          {%- if states.sensor.amber_todays_heating_cooling_total_cost.state|is_number 
              and states.sensor.sa_data_by_5min_load_air_conditioner_total.state|is_number -%}
            {%- if states.sensor.sa_data_by_5min_load_air_conditioner_total.state|float(0.0) > 100.0 -%}
              {{- ( states.sensor.amber_todays_heating_cooling_total_cost.state|float(0.0) 
                    / states.sensor.sa_data_by_5min_load_air_conditioner_total.state|float(1.0) 
                    * 1000.0 ) | round(3) 
                -}}
            {%- else -%}
              {{- this.state|default(0.0) -}}
            {%- endif -%}
          {%- else -%}
            unavailable
          {%- endif -%}
        attribute_templates:
          state_class: measure
          time_stamp: "{{- states.sensor.sa_data_by_5min_time_stamp.state -}}"


template:
  - trigger:
      - platform: state
        entity_id: sensor.sa_todays_heating_cooling_generated
        attribute: time_stamp
    sensor:
      - name: "amber_todays_heating_cooling_generated_inc_cost"
        unique_id: amber_todays_heating_cooling_generated_inc_cost
        state: >-
          {%- if states.sensor.sa_todays_heating_cooling_generated.attributes.ac_energy_last5min|float(0.0) > 0.0 -%}
            {{- states.sensor.amber_todays_heating_cooling_generated_inc_cost.attributes.last_price|float(0.0) 
                * states.sensor.sa_todays_heating_cooling_generated.attributes.ac_energy_last5min|float(0.0) 
                / 1000.0 
              -}}
          {%- else -%}
            0.0
          {%- endif -%}
        attributes:
          time_stamp: "{{- states.sensor.sa_data_by_5min_time_stamp.state -}}"
          last_price: "{{- states.sensor.amber12ayrst_feed_in_price.state|default(0.0) -}}"

  - trigger:
      - platform: state
        entity_id: sensor.sa_todays_heating_cooling_imported
        attribute: time_stamp
    sensor:
      - name: "amber_todays_heating_cooling_imported_inc_cost"
        unique_id: amber_todays_heating_cooling_imported_inc_cost
        state: >-
          {%- if states.sensor.sa_todays_heating_cooling_imported.attributes.ac_energy_last5min|float(0.0) > 0.0 -%}
            {{- states.sensor.amber_todays_heating_cooling_imported_inc_cost.attributes.last_price|float(0.0) 
                * states.sensor.sa_todays_heating_cooling_imported.attributes.ac_energy_last5min|float(0.0) 
                / 1000.0 
              -}}
          {%- else -%}
            0.0
          {%- endif -%}
        attributes: 
          time_stamp: "{{- states.sensor.sa_data_by_5min_time_stamp.state -}}"
          last_price: "{{- states.sensor.amber12ayrst_general_price.state|default(0.0) -}}"

  - trigger:
      - platform: state
        entity_id: sensor.amber_todays_heating_cooling_generated_inc_cost
        attribute: time_stamp
      - platform: state
        entity_id: binary_sensor.amber_meter_reset
        from:
          - "off"
          - "unknown"
          - "unavailable"
        to: "on"
    sensor:
      - name: "Heating Cooling Generated Cost"
        unique_id: amber_todays_heating_cooling_generated_cost
        unit_of_measurement: "AUD"
        device_class: "monetary"
        icon: mdi:cash
        state: >-
          {%- if states.binary_sensor.amber_meter_reset.state == "on" -%}
            0.0
          {%- else -%}
            {%- if states.sensor.amber_todays_heating_cooling_generated_inc_cost.state|is_number -%}
              {{- states.sensor.amber_todays_heating_cooling_generated_cost.state|float(0.0)
                  + states.sensor.amber_todays_heating_cooling_generated_inc_cost.state|float(0.0) 
                -}}
            {%- else -%}
              {{- states.sensor.amber_todays_heating_cooling_generated_cost.state
                  if states.sensor.amber_todays_heating_cooling_generated_cost.state|is_number 
                  else 0.0 
                -}}
            {%- endif -%}
          {%- endif -%}
        attributes: 
          state_class: total
          time_stamp: >-
            {{- states.binary_sensor.amber_meter_reset.attributes.time_stamp 
                if states.binary_sensor.amber_meter_reset.state == "on" 
                else states.sensor.sa_data_by_5min_time_stamp.state 
              -}}

  - trigger:
      - platform: state
        entity_id: sensor.amber_todays_heating_cooling_imported_inc_cost
        attribute: time_stamp
      - platform: state
        entity_id: binary_sensor.amber_meter_reset
        from:
          - "off"
          - "unknown"
          - "unavailable"
        to: "on"
    sensor:
      - name: "Heating Cooling Imported Cost"
        unique_id: amber_todays_heating_cooling_imported_cost
        unit_of_measurement: "AUD"
        device_class: "monetary"
        icon: mdi:cash
        state: >-
          {%- if states.binary_sensor.amber_meter_reset.state == "on" -%}
            0.0
          {%- else -%}
            {%- if states.sensor.amber_todays_heating_cooling_imported_inc_cost.state|is_number -%}
              {{- states.sensor.amber_todays_heating_cooling_imported_cost.state|float(0.0)
                  + states.sensor.amber_todays_heating_cooling_imported_inc_cost.state|float(0.0) 
                -}}
            {%- else -%}
              {{- states.sensor.amber_todays_heating_cooling_imported_cost.state
                  if states.sensor.amber_todays_heating_cooling_imported_cost.state|is_number 
                  else 0.0 
                -}}
            {%- endif -%}
          {%- endif -%}
        attributes: 
          state_class: total
          time_stamp: >-
            {{- states.binary_sensor.amber_meter_reset.attributes.time_stamp 
                if states.binary_sensor.amber_meter_reset.state == "on" 
                else states.sensor.sa_data_by_5min_time_stamp.state 
              -}}

# -----------------------------------------------------------------------------
